# Generated by Django 4.0.3 on 2022-03-17 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('province_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('track_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.parcel')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_num', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('street_num', models.CharField(max_length=100)),
                ('province_id', models.CharField(max_length=100)),
                ('city_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.parcel')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_num', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('street_num', models.CharField(max_length=100)),
                ('province_id', models.CharField(max_length=100)),
                ('city_id', models.CharField(max_length=100)),
            ],
        ),
    ]
