# Generated by Django 4.0.3 on 2022-04-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_sender_parcel_delete_receiver_delete_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='province_id',
            new_name='city_id',
        ),
    ]
