# Generated by Django 4.0.3 on 2022-05-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_receiver_trackingcode_sender_trackingcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='trackingcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sender',
            name='trackingcode',
            field=models.CharField(max_length=100),
        ),
    ]
