# Generated by Django 4.0.3 on 2022-03-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_access', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_creds',
            new_name='credentials',
        ),
    ]
