# Generated by Django 4.0.3 on 2022-03-31 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_access', '0002_rename_admin_creds_credentials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='credentials',
            new_name='credential',
        ),
    ]
